export const Users = [
    { id: 1, profilePicture: "assets/person/1.webp", username: "Malik Johnson" },
    { id: 2, profilePicture: "assets/person/2.webp", username: "Aisha Ndiaye" },
    { id: 3, profilePicture: "assets/person/3.webp", username: "Derrick Brown" },
    { id: 4, profilePicture: "assets/person/4.webp", username: "Fatou Diop" },
    { id: 5, profilePicture: "assets/person/5.webp", username: "Jamal Walker" },
    { id: 6, profilePicture: "assets/person/6.webp", username: "Chinwe Okoro" },
    { id: 7, profilePicture: "assets/person/7.webp", username: "DeShawn Taylor" },
    { id: 8, profilePicture: "assets/person/8.webp", username: "Grace Mbaye" },
    { id: 9, profilePicture: "assets/person/9.webp", username: "Tyrese Carter" },
    { id: 10, profilePicture: "assets/person/10.webp", username: "Naomi Williams" },
];

export const Posts = [
  {
    id: 1,
    desc: "Love For All, Hatred For None.",
    photo: "assets/posts/1.webp",
    date: "5 mins ago",
    userId: 1,
    like: 32,
    comment: 5,
  },
  {
    id: 2,
    photo: "assets/posts/2.webp",
    date: "15 mins ago",
    userId: 2,
    like: 2,
    comment: 0,
  },
  {
    id: 3,
    desc: "Every moment is a fresh beginning.",
    photo: "assets/posts/3.webp",
    date: "1 hour ago",
    userId: 3,
    like: 61,
    comment: 3,
  },
  {
    id: 4,
    photo: "assets/posts/4.webp",
    date: "4 hours ago",
    userId: 4,
    like: 7,
    comment: 2,
  },
  {
    id: 5,
    photo: "assets/posts/5.webp",
    date: "5 hours ago",
    userId: 5,
    like: 23,
    comment: 4,
  },
  {
    id: 6,
    photo: "assets/posts/6.webp",
    date: "1 day ago",
    userId: 6,
    like: 44,
    comment: 1,
  },
  {
    id: 7,
    desc: "Never regret anything that made you smile.",
    photo: "assets/posts/7.webp",
    date: "2 days ago",
    userId: 7,
    like: 52,
    comment: 6,
  },
  {
    id: 8,
    photo: "assets/posts/8.webp",
    date: "3 days ago",
    userId: 8,
    like: 15,
    comment: 2,
  },
  {
    id: 9,
    desc: "Change the world by being yourself.",
    photo: "assets/posts/9.webp",
    date: "5 days ago",
    userId: 9,
    like: 11,
    comment: 1,
  },
  {
    id: 10,
    photo: "assets/posts/10.webp",
    date: "1 week ago",
    userId: 10,
    like: 104,
    comment: 8,
  },
];